In [1]:
import numpy as np

## Numpy Arrays

In [2]:
myList = [20,30,40]

In [3]:
type(myList)

list

In [4]:
np.array(myList)

array([20, 30, 40])

In [5]:
type(np.array(myList))

numpy.ndarray

In [6]:
martixList = [[10,20,30],[20,30,40],[30,40,50]]

In [7]:
type(martixList)

list

In [8]:
martixList[1]

[20, 30, 40]

In [9]:
martixList[1][0]

20

In [10]:
np.array(martixList)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

## Arange

In [11]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

## Zeros

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
np.zeros((9,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## Ones


In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

## Linspace

In [22]:
# esit olarak boyutlandirilmis , esit olarak aralik birakilmis sekilde dizi olusturur

In [23]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [26]:
np.linspace(0,20,2)

array([ 0., 20.])

In [29]:
np.linspace(0,20,2)

array([ 0., 20.])

In [30]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [27]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [28]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

## Eye

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## Random

In [39]:
np.random.randn(8)

array([ 0.25250198, -3.62361431,  0.51709405,  0.42801317, -0.04815379,
       -0.51919104,  0.0560461 ,  0.89917148])

In [36]:
np.random.randn(4)

array([ 0.25350571,  0.04937822, -0.18194694, -0.51757863])

In [37]:
np.random.randn(4,4)

array([[ 1.73238165,  0.69788108,  0.33281443, -0.61121683],
       [-1.06053515,  1.06012812, -1.92959311, -0.28075397],
       [-0.03040117, -0.57664935, -0.93872844,  0.58819444],
       [-0.44985211, -0.60911199, -0.20880473,  0.09318433]])

In [47]:
np.random.randint(1,10)

1

In [49]:
np.random.randint(1,300,5)

array([197, 264, 191, 136, 171], dtype=int32)

In [50]:
myNumpyArray = np.arange(30)

In [51]:
myNumpyArray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
myRandomArray = np.random.randint(0,100,30)

In [70]:
myRandomArray

array([87, 77, 84, 86, 53, 48, 97,  1,  0, 80, 13, 50, 50, 93, 37, 17, 79,
       92, 71, 97, 92, 70, 32, 71, 43, 73, 35, 72, 87, 90], dtype=int32)

## Numpy Array Methods

In [58]:
myNumpyArray.reshape(5,5)

ValueError: cannot reshape array of size 30 into shape (5,5)

In [59]:
myNumpyArray.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [60]:
myNumpyArray.reshape(6,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [64]:
myNumpyArray.max()

np.int64(29)

In [62]:
print(myNumpyArray.max())

29


In [63]:
print(myNumpyArray.min())

0


In [65]:
print(myRandomArray.max())

97


In [66]:
print(myRandomArray.min())

0


In [69]:
print(myRandomArray.argmax())

6


In [71]:
print(myRandomArray.argmin())

8


In [73]:
myNumpyArray.shape

(30,)

In [76]:
reshapedArray = myNumpyArray.reshape(5,6)

In [77]:
reshapedArray

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [78]:
reshapedArray.shape

(5, 6)